Updated.

diff --git a/lcopy2/src/lcopy-checkout b/lcopy2/src/lcopy-checkout
--- a/lcopy2/src/lcopy-checkout
+++ b/lcopy2/src/lcopy-checkout
@@ -3,20 +3,29 @@
 source liblcopy.sh ||  exit 1
 
 
-OUTPUT_DIR=
+OUTPUT_DIR=.
 
 INPUT=
 LCOPY_VCS=
 LCOPY_PACKAGE=
 LCOPY_BRANCH=
+NO_ERROR_MESSAGE_IF_EXISTING=
+
+readonly ERROR=1
+readonly EXISTED=2
 
 function print_usage
 {
     echo "Usage: "
     echo "$0 --help|-h"
-    echo "$0 [--output-dir=OUTPUT-DIR] FILE.lcopy"
+    echo "$0 [--output-dir=OUTPUT-DIR] [--no-error-message-if-existing] FILE.lcopy"
     echo ""
     echo "(taking checkout configurations from stdin)"
+    echo "Exit status: "
+    echo "	0: Successful"
+    echo "	1: Error"
+    echo "	2: Directory for checkout out to exists"
+    
 }
 
 function parse_arguments
@@ -29,21 +38,13 @@ function parse_arguments
 		;;
 	    (--output-dir=*)
                 OUTPUT_DIR=${1/--output-dir=}
-		if ! [ -d "$OUTPUT_DIR" ]; then
-		    echo "no such directory: $OUTPUT_DIR" 1>&2
-		    exit 1
-		fi
-		
-		if ! [ -w "$OUTPUT_DIR" ]; then
-		    echo "cannot write to: $OUTPUT_DIR" 1>&2
-		    exit 1
-		fi
-		    
                 ;;
+	    --no-error-message-if-existing)
+	        NO_ERROR_MESSAGE_IF_EXISTING=yes
 	    --*)
 		echo "unknown option: $1" 1>&2
 		print_usage 1>&2
-		exit 1
+		exit $ERROR
 		;;
 	    *)
 		INPUT=$1
@@ -51,7 +52,7 @@ function parse_arguments
 
 		if ! [ -r "$INPUT" ]; then
 		    echo "cannot read: $INPUT" 1>&2
-		    exit 1
+		    exit $ERROR
 		fi
 		break
 		;;
@@ -59,16 +60,26 @@ function parse_arguments
 	shift
     done
 
+    if ! [ -d "$OUTPUT_DIR" ]; then
+	echo "no such directory: $OUTPUT_DIR" 1>&2
+	exit $ERROR
+    fi
+    
+    if ! [ -w "$OUTPUT_DIR" ]; then
+	echo "cannot write to: $OUTPUT_DIR" 1>&2
+	exit $ERROR
+    fi
+		  
     if [ -z "$INPUT" ]; then
 	echo "no lcopy file given" 1>&2
 	print_usage 1>&2
-	exit 1
+	exit $ERROR
     fi
 
     if [ "$#" -gt 0 ]; then
 	echo "too many arguments: $@" 1>&2
 	print_usage 1>&2
-	exit 1
+	exit $ERROR
     fi
 }
 
@@ -78,7 +89,7 @@ function load_input
 
     if [ -z "$LCOPY_VCS" ]; then
 	echo "no LCOPY_VCS in $INPUT" 2>&1
-	exit 1
+	exit $ERROR
     else
 	local vcs_found
 	for v in $(lcopy_backends_list); do
@@ -89,19 +100,19 @@ function load_input
 	done
 	if [ -z "$vcs_found" ]; then
 	    echo "unsupported vcs: $LCOPY_VCS" 1>&2
-	    exit 1
+	    exit $ERROR
 	fi
     fi
 
     
     if [ -z "$LCOPY_PACKAGE" ]; then
 	echo "no LCOPY_PACKAGE in $INPUT" 2>&1
-	exit 1
+	exit $ERROR
     fi
     
     if [ -z "$LCOPY_BRANCH" ]; then
 	echo "no LCOPY_BRANCH in $INPUT" 2>&1
-	exit 1
+	exit $ERROR
     fi
 }
 
@@ -127,8 +138,10 @@ function main
     load_input $INPUT
 
     if [ -d "${OUTPUT_DIR}/${LCOPY_PACKAGE:0:1}/${LCOPY_PACKAGE}/${LCOPY_BRANCH}" ]; then
-	echo "${OUTPUT_DIR}/${LCOPY_PACKAGE:0:1}/${LCOPY_PACKAGE}/${LCOPY_BRANCH} already exits" 1>&2
-	return 1
+	if [ "${NO_ERROR_MESSAGE_IF_EXISTING}" != "yes" ]; then
+	    echo "${OUTPUT_DIR}/${LCOPY_PACKAGE:0:1}/${LCOPY_PACKAGE}/${LCOPY_BRANCH} already exits" 1>&2
+	fi
+	return $EXISTED
     fi
 
     
@@ -152,8 +165,11 @@ function main
 
     if [ "$status" = "0" ]; then
 	lcopy_srpmix_plugin "${base_dir}"
-	transfer "${base_dir} "
-	status=$?
+	if transfer "${base_dir} "; then
+	    status=0
+	else
+	    status=$ERROR
+	fi
     fi
     return $status
 }
