Pick password entry from .cvspass.

diff --git a/lcopy/trunk/src/lcopy-rebirth b/lcopy/trunk/src/lcopy-rebirth
--- a/lcopy/trunk/src/lcopy-rebirth
+++ b/lcopy/trunk/src/lcopy-rebirth
@@ -67,7 +67,9 @@ function generate_cvs_cmdline
     cvs_repo=
     top_dir=`pwd`
     cvs_dir=$(basename  ${top_dir})
-    
+    cvs_root_rx=
+    cvs_pass=
+
     (cd CVS; 
 	if test -f Root; then
 	    cvs_root=`cat Root`
@@ -82,14 +84,21 @@ function generate_cvs_cmdline
 	    echo "cannot find cvs Repository file" 1>&2
 	    return 1
 	fi
-	
-	# TODO
-	# cvs login
-	# EXPECT is needed.
-	# echo '# 1'
-	# echo 'echo | ' cvs -d"${cvs_root}" login
-	
+
+
 	echo "# [0] ${top_dir}"
+	
+	cvs_root_rx=`echo ${cvs_root} | sed -e 's|\(.*\):/\(.*\)|\1:[0-9]*/\2|'`
+	cvs_pass=`grep "${cvs_root_rx}" ~/.cvspass 2>/dev/null`
+	if [ $? == 0 ]; then
+            cat <<EOF
+fgrep '${cvs_pass}' ~/.cvspass > /dev/null 2>&1 \\
+|| echo '${cvs_pass}' >> ~/.cvspass
+EOF
+        else
+	    echo "# [1] cannot find password entry for ${top_dir}"
+	fi
+
 	echo cvs -d"${cvs_root}" checkout -P -d ${cvs_dir} ${cvs_repo}
 	return 0
 	)
