updated

diff --git a/sbuild/src/sbuild b/sbuild/src/sbuild
--- a/sbuild/src/sbuild
+++ b/sbuild/src/sbuild
@@ -1,31 +1,23 @@
 #!/bin/bash
+# REQUIRE: rsync
+# verify_command srpmix
 
 PKGCONFDIR=/etc/sbuild
 PKGDATADIR=/usr/share/sbuild
 LIST_MAKER=cat
 DONT_CREATEREPO=
 RSYNC=rsync
-SOP_CONF=sop.cf
 
-if ! source ${PKGCONFDIR}/sbuild.cf; then
-    echo "failed to read ${PKGCONFDIR}/sbulid.cf" 1>&2
-    exit 1
-fi
+SBUILD_CONF=${PKGCONFDIR}/sbulid.cf
+SOP_CONF=/etc/sop/sop.cf
 
-if [ "x$1" != x ] && [ -r "$1/${SOP_CONF}" ]; then
-    source "$1/${SOP_CONF}"
-elif test -f /etc/sop/${SOP_CONF}; then
-    source /etc/sop/${SOP_CONF}
-else
-    echo "Cannot load ${SOP_CONF} file" 1>&2
-    exit 1
-fi
 
-# verify_command srpmix
 function print_usage
 {
     echo "Usage: "
-    echo "  sbuild [--tmpdir=TMPDIR]"
+    echo "  sbuild --help"
+    echo "  sbuild [--sbuild-conf=FILE] [--sop-conf=FILE]"
+    echo "         [--tmpdir=TMPDIR]"
     echo "         [--output-dir=OUTPUTDIR]"
     echo "         [--release=RELEASE]"
     echo "         [--debug]"
@@ -35,7 +27,7 @@ function print_usage
     echo "         [--all-pkgs]"
     echo "         [--createrepo-only]"
     echo "         [--dont-createrepo]"
-    echo "         [--use-tmpfs]"
+    echo "         [--use-tmpfs=GBYTE]"
 }
 
 function parse_arguments
@@ -46,27 +38,33 @@ function parse_arguments
 		print_usage
 		exit 0
 		;;
-	    --tmpdir=*)
-                SBUILD_TMPDIR="$(echo $1 | sed -e 's/--tmpdir=//')"
+	    --sbuild-conf=*)
+                SBUILD_CONF=${1/--sbuild-conf=/}
 		;;
-	    --outputdir=*)
-	        SBUILD_OUTPUTDIR="$(echo $1 | sed -e 's/--outputdir=//')"
+	    --sop-conf=*)
+                SOP_CONF=${1/--sop-conf=/}
+                ;;
+	    --tmpdir=*)
+                SBUILD_TMPDIR=${1/--tmpdir=/}
+		;;
+	    --output-dir=*)
+	        SBUILD_OUTPUTDIR=${1/--output-dir=/}
 		;;
 	    --release=*)
                 # RELEASE=`date +%Y%m%d`
-	        SBUILD_RELEASE="$(echo $1 | sed -e 's/--release=//')"
+	        SBUILD_RELEASE=${1/--release=/}
 		;;
 	    --debug)
 	        SBUILD_DEBUG=y
                 ;;
             --blacklist-dir=*)
-	        SBUILD_BLACKLISTDIR="$(echo $1 | sed -e 's/--blacklist-dir=//')"
+	        SBUILD_BLACKLISTDIR=${1/--blacklist-dir=/}
 	        ;;
             --tstamp-dir=*)
-	        SBUILD_TSTAMPDIR="$(echo $1 | sed -e 's/--tstamp-dir=//')"
+	        SBUILD_TSTAMPDIR=${1/--tstamp-dir=/}
 	        ;;
             --vpath-file=*)
-	        SBUILD_VPATHFILE="$(echo $1 | sed -e 's/--vpath-file=//')"
+	        SBUILD_VPATHFILE=${1/--vpath-file=/}
 		;;
 	    --all-pkgs)
 	        LIST_MAKER=${PKGDATADIR}/sbuild-srpm-list.sh
@@ -78,9 +76,16 @@ function parse_arguments
             --dont-createrepo)
 	        DONT_CREATEREPO=1
 		;;
-	    --use-tmpfs)
-	        if ! { mount | grep ${SBUILD_TMPDIR}; } > /dev/null; then
-		    mount -t tmpfs -o size=2G tmpfs "${SBUILD_TMPDIR}"
+	    --use-tmpfs=*)
+	        local tmpfs_size=${1/--use-tmpfs=/}
+	        if { mount | grep ${SBUILD_TMPDIR}; } > /dev/null; then
+		    echo "A file system is already mounted on ${SBUILD_TMPDIR}" 1>&2
+		    exit 1
+		else
+		    if ! mount -t tmpfs -o size=${tmpfs_size}G tmpfs "${SBUILD_TMPDIR}"; then
+			echo "Failed in mounting tmpfs on "${SBUILD_TMPDIR}" with size ${tmpfs_size}G" 1>&2
+			exit
+		    fi
 		fi
 		;;
             *)
@@ -90,6 +95,20 @@ function parse_arguments
         esac
 	shift
     done
+
+    if test -f "${SBUILD_CONF}"; then
+	source "${SBUILD_CONF}"
+    else
+	echo "Cannot load ${SBUILD_CONF} file" 1>&2
+	exit 1
+    fi
+
+    if test -f "${SOP_CONF}"; then
+	source "${SOP_CONF}"
+    else
+	echo "Cannot load ${SOP_CONF} file" 1>&2
+	exit 1
+    fi
 }
 
 
@@ -105,8 +124,7 @@ function run_make
 	SBUILD_VPATHFILE=${SBUILD_TSTAMPDIR}/vpath.list
     fi
 
-    $LIST_MAKER \
-    | while read f; do
+    while read f; do
 	f=$(basename $f)
 	h=$(echo $f | sed 's/\(.\).*/\1/')
 
@@ -116,6 +134,7 @@ function run_make
 	    install -d ${SBUILD_TSTAMPDIR}/$h
 	fi
 
+	# TODO -l should be given externally
 	${PKGDATADIR}/sbuild.mk			\
             DEBUG=$DEBUG			\
             TMPDIR=${SBUILD_TMPDIR}		\
@@ -134,7 +153,7 @@ function run_make
 
 function run_creterepo
 {
-    ${PKGDATADIR}/sbuild-createrepo.mk -C $SBUILD_OUTPUTDIR
+    ${PKGDATADIR}/sbuild-createrepo.mk -C ${SBUILD_OUTPUTDIR}
 }
 
 function run_rsync
@@ -153,7 +172,7 @@ function main
 
     r=$?
 
-    run_rsync
+    $LIST_MAKER | run_rsync
 
     if test "x${DONT_CREATEREPO}" != x; then
 	return $r;
