Updated.

diff --git a/prelcopy/src/prelcopy b/prelcopy/src/prelcopy
--- a/prelcopy/src/prelcopy
+++ b/prelcopy/src/prelcopy
@@ -1,19 +1,15 @@
 #!/bin/bash
 
 SCM=/usr/share/prelcopy/prelcopy.scm
-if ! [ -r $SCM ]; then
-    echo "Cannot find prelcopy.scm" 1>&2
-    exit 1
-fi
-
 CF=
 OUTPUT_DIR=
+CLASSES_DIR=/usr/libexec/prelcopy/classes
 
 function print_usage
 {
     echo "Usage: "
-    echo "	$0 [--output-dir=OUTPUT-DIR] CF.prelcopy"
-    echo "      $0 --help"
+    echo "	$0 [--output-dir=OUTPUT-DIR] [--scm=PRELCOPY.SCM] [--classes-dir=CLASSES_DIR] CF.prelcopy"
+    echo "	$0 --help"
 
     exit $1
 }
@@ -34,6 +30,12 @@ function parse_arguments
 		    exit 1
 		fi
 	        ;;
+	    (--scm=*)
+	       SCM=${1/--scm=}
+	       ;;
+	    (--classes-dir=*)
+	       CLASSES_DIR=${1/--classes-dir=}
+	       ;;
 	    --*)
 		echo "No such option: $1" 1>&2 
 		print_usage 1 1>&2
@@ -56,6 +58,16 @@ function parse_arguments
 	echo "Too many arguments" 1>&2
 	print_usage 1 1>&2
     fi
+
+    if ! [ -r $SCM ]; then
+	echo "Cannot find prelcopy.scm" 1>&2
+	exit 1
+    fi
+
+    if ! [ -d $CLASSES_DIR ]; then
+	echo "Cannot find classes directory: $CLASSES_DIR" 1>&2
+	exit 1
+    fi
 }
 
 function main
@@ -72,7 +84,7 @@ function main
 	exit 1
     fi
 
-    classfile="/usr/libexec/prelcopy/classes/$PRELCOPY_CLASS"    
+    classfile="$CLASSES_DIR/$PRELCOPY_CLASS"    
     if ! [ -x "$classfile" ]; then
 	echo "No such class: $classfile" 1>&2
 	exit 1
