updated

diff --git a/sop/src/cron/sop-060-build b/sop/src/cron/sop-060-build
--- a/sop/src/cron/sop-060-build
+++ b/sop/src/cron/sop-060-build
@@ -1,1 +1,41 @@
 #!/bin/bash
+
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+SOPCONFDIR=/etc/sop
+CONF=sop.cf
+PKGDATADIR=/usr/share/sop
+
+if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
+    SOPCONFDIR=$1
+    source "$1/${CONF}"
+elif test -f ${SOPCONFDIR}/${CONF}; then
+    source ${SOPCONFDIR}/${CONF}
+else
+    echo "Cannot load ${CONF} file" 1>&2
+    exit 1
+fi
+
+function main
+{
+    if test "x$SOP_ENABLE_BUILD" != xyes; then
+	return 0
+    fi
+
+    if test -z "$SOP_BUILD_ROOT"; then
+	echo "SOP_BUILD_ROOT is not given" 1>&2
+	return 1
+    fi
+    if ! which sbuild > /dev/null 2>&1; then
+	echo "sbuild not found" 1>&2
+	return 1
+    fi
+
+    mkdir -p "$SOP_BUILD_ROOT"
+    (
+	cd "$SOP_BUILD_ROOT"
+	sbuild $SOP_SBUILD_OPTIONS
+    )
+}
+
+time main
+
