updated

diff --git a/sop/src/cron/sop-010-mirror b/sop/src/cron/sop-010-mirror
--- a/sop/src/cron/sop-010-mirror
+++ b/sop/src/cron/sop-010-mirror
@@ -1,1 +1,75 @@
 #!/bin/bash
+
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+CONF=sop.cf
+
+if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
+    source "$1/${CONF}"
+elif test -f /etc/sop/${CONF}; then
+    source /etc/sop/${CONF}
+else
+    echo "Cannot load ${CONF} file" 1>&2
+    exit 1
+fi
+
+
+function count
+{
+    echo $#
+}
+
+function verify_targets
+{
+    if test $(count "${MIRROR_TARGET_HOST[@]}") = $(count "${MIRROR_TARGET_PATH[@]}") &&
+	test $(count "${MIRROR_TARGET_HOST[@]}") = $(count "${MIRROR_TARGET_PATTERN[@]}"); then
+	return 0
+    else
+	return 1
+    fi
+}
+
+function mirror
+{
+    local host=$1
+    local path=$2
+    local pattern=$3
+
+    local odir="${MIRROR_DIR}/${host}"
+    local ldir="${MIRROR_DIR}/log"
+    local date=$(date --rfc-3339=date)
+
+    if ! test -d $odir; then
+	mkdir -p $odir
+    fi
+
+    if ! test -d $ldir; then
+	mkdir -p $ldir
+    fi
+
+    (
+	cd ${odir}
+	wget -nH --cut-dirs=2 --mirror ftp://${host}${path} -A "${pattern}" \
+            -o ${ldir}/${host}.${date}.log
+	)
+}
+
+function main
+{
+    local n
+
+    if ! verify_targets; then
+	echo "The number of elements of MIRROR_TARGET_ arrays are not matched" 2>&1
+	exit 1;
+    fi
+    
+    let n=$(count "${MIRROR_TARGET_HOST[@]}")
+    let i=0
+    while [ $i -lt $n ]; do
+	mirror "${MIRROR_TARGET_HOST[$i]}" "${MIRROR_TARGET_PATH[$i]}" "${MIRROR_TARGET_PATTERN[$i]}" 
+	let i=i+1
+    done
+
+    return 0
+}
+
+time main
diff --git a/sop/src/cron/sop-020-hardlink-mirror b/sop/src/cron/sop-020-hardlink-mirror
--- a/sop/src/cron/sop-020-hardlink-mirror
+++ b/sop/src/cron/sop-020-hardlink-mirror
@@ -1,1 +1,48 @@
 #!/bin/bash
+
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+HARDLINK=hardlink
+CONF=sop.cf
+
+if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
+    source "$1/${CONF}"
+elif test -f /etc/sop/${CONF}; then
+    source /etc/sop/${CONF}
+else
+    echo "Cannot load ${CONF} file" 1>&2
+    exit 1
+fi
+
+function count
+{
+    echo $#
+}
+
+function verify_targets
+{
+    if test $(count "${MIRROR_TARGET_HOST[@]}") = $(count "${MIRROR_TARGET_PATH[@]}") &&
+	test $(count "${MIRROR_TARGET_HOST[@]}") = $(count "${MIRROR_TARGET_PATTERN[@]}"); then
+	return 0
+    else
+	return 1
+    fi
+}
+
+function main
+{
+    local n
+
+    if ! verify_targets; then
+	echo "The number of elements of MIRROR_TARGET_ arrays are not matched" 2>&1
+	exit 1;
+    fi
+    
+    let n=$(count "${MIRROR_TARGET_HOST[@]}")
+    let i=0
+    while [ $i -lt $n ]; do
+	${HARDLINK} ${MIRROR_DIR}/${MIRROR_TARGET_HOST[$i]}
+	let i=i+1
+    done
+}
+
+time main
diff --git a/sop/src/cron/sop-030-backup b/sop/src/cron/sop-030-backup
--- a/sop/src/cron/sop-030-backup
+++ b/sop/src/cron/sop-030-backup
@@ -1,1 +1,52 @@
 #!/bin/bash
+
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+RSYNC=rsync
+CONF=sop.cf
+
+if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
+    source "$1/${CONF}"
+elif test -f /etc/sop/${CONF}; then
+    source /etc/sop/${CONF}
+else
+    echo "Cannot load ${CONF} file" 1>&2
+    exit 1
+fi
+
+function count
+{
+    echo $#
+}
+
+function verify_src
+{
+    if test $(count "${BACKUP_SRC[@]}") = $(count "${BACKUP_DST[@]}"); then
+	return 0
+    else
+	return 1
+    fi
+}
+
+function main
+{
+    local n
+
+    if ! verify_src; then
+	echo "The number of elements of BACKUP_ arrays are not matched" 2>&1
+	exit 1
+    fi
+
+    let n=$(count "${BACKUP_SRC[@]}")
+    let i=0
+    while [ $i -lt $n ]; do
+	if echo "${BACKUP_DST[$i]}" | grep -e '.*/$' > /dev/null 2>&1; then
+	    mkdir -p $(driname "${BACKUP_DST[$i]}")
+	else
+	    mkdir -p "${BACKUP_DST[$i]}"
+	fi
+	${RSYNC} -auvH "${BACKUP_SRC[$i]}" "${BACKUP_DST[$i]}" 2>&1 |tee "/tmp/rsync${i}.log"
+	let i=i+1
+    done
+}
+
+time main
diff --git a/sop/src/cron/sop-040-hardlink-backup b/sop/src/cron/sop-040-hardlink-backup
--- a/sop/src/cron/sop-040-hardlink-backup
+++ b/sop/src/cron/sop-040-hardlink-backup
@@ -1,1 +1,32 @@
 #!/bin/bash
+PATH=/bin:/usr/bin:/sbin:/usr/sbin
+HARDLINK=hardlink
+CONF=sop.cf
+
+if [ "x$1" != x ] && [ -r "$1/${CONF}" ]; then
+    source "$1/${CONF}"
+elif test -f /etc/sop/${CONF}; then
+    source /etc/sop/${CONF}
+else
+    echo "Cannot load ${CONF} file" 1>&2
+    exit 1
+fi
+
+function count
+{
+    echo $#
+}
+
+function main
+{
+    local n
+
+    let n=$(count "${BACKUP_DST[@]}")
+    let i=0
+    while [ $i -lt $n ]; do
+	${HARDLINK} ${BACKUP_DST[$i]}
+	let i=i+1
+    done
+}
+
+time main
