Code cleanup

diff --git a/srpmix/trunk/src/libsrpmix.sh.in b/srpmix/trunk/src/libsrpmix.sh.in
--- a/srpmix/trunk/src/libsrpmix.sh.in
+++ b/srpmix/trunk/src/libsrpmix.sh.in
@@ -28,6 +28,25 @@ SRPMIX_SOURCES_DIR="${SRPMIX_ROOT_DIR}/sources"
 SRPMIX_VERSION=@VERSION@
 SRPMIX_RELEASE=0
 
+function srpmix_abort
+{
+    echo "*** ABORT..." "$@" 1>&2
+    exit 1
+}
+
+function srpmix_verify_commands
+{
+    while [ $# -gt 0 ]; do
+	if which $1 > /dev/null 2>&1; then
+	    :
+	else
+	    echo "cannot find $1" 1>&2
+	    srpmix_abort
+	fi
+	shift 
+    done
+}
+
 function srpmix_build_wrapped_name
 {
     local package=$1
@@ -36,6 +55,54 @@ function srpmix_build_wrapped_name
 
     wrapped_name="$package-$version-$release-srpmix"
     echo ${wrapped_name}
+}
+
+# srpmix_srcdir package version release
+# srpmix_srcdir prints the source directory for (package, version, release)
+function srpmix_srcdir
+{
+    local package=$1
+    local version=$2
+    local release=$3
+
+    local pkg_hash=$(echo $package | sed  's/\(^.\).*/\1/')
+    local pkg_root="${SRPMIX_SOURCES_DIR}"/"${pkg_hash}"/"$package"
+    
+    echo "${pkg_root}"/"$version-$release"
+}
+
+srpmix_distmap_to_pvr_script='
+(let ((kget (lambda (kl ky)
+	      (cond ((null? kl) #f)
+		    ((eq? (car kl) ky) (cadr kl))
+		    (else (kget (cdr kl) ky))))
+	    ))
+  (let loop ((r (read)))
+       (unless (eof-object? r)
+	 (when (and (list? r)
+		    (eq? (car r) `srpmix-wrap)
+		    (not (null? (cdr r)))
+		    (eq? (cadr r) `name))
+	   (format #t "~a ~a ~a\n" 
+		   (kget r :package)
+		   (kget r :version)
+		   (kget r :release)))
+	 (loop (read)))))'
+
+GOSH=gosh
+# Print :package, :version, and :release field of dist-mapping es espression.
+# Example Input:
+# (srpmix-wrap name :target-srpm "ElectricFence-2.2.2-20.2.src.rpm" 
+#                   :package "ElectricFence" 
+#                   :version "2.2.2" 
+#                   :release "20.2" 
+#                   :wrapped-name "ElectricFence-2.2.2-20.2-srpmix")
+# Expected Output:
+# ElectricFence 2.2.2 20.2
+#
+function srpmix_distmap_to_pvr
+{
+    ${GOSH} -e "${srpmix_distmap_to_pvr_script}"
 }
 
 ########################################################################
@@ -199,20 +266,6 @@ function es_print_sans_newline
     fi
 
     printf ")"
-}
-
-# srpmix_srcdir package version release
-# srpmix_srcdir prints the source directory for (package, version, release)
-function srpmix_srcdir
-{
-    local package=$1
-    local version=$2
-    local release=$3
-
-    local pkg_hash=$(echo $package | sed  's/\(^.\).*/\1/')
-    local pkg_root="${SRPMIX_SOURCES_DIR}"/"${pkg_hash}"/"$package"
-    
-    echo "${pkg_root}"/"$version-$release"
 }
 
 #
diff --git a/srpmix/trunk/src/srpmix-weakview-dist b/srpmix/trunk/src/srpmix-weakview-dist
--- a/srpmix/trunk/src/srpmix-weakview-dist
+++ b/srpmix/trunk/src/srpmix-weakview-dist
@@ -24,12 +24,10 @@
 ########################################################################
 
 RPMBUILD=rpmbuild
-GOSH=gosh
 LIBSRPMIX=libsrpmix.sh
 NAME=
 OUTPUTDIR=
 TMPDIR=
-RELEASE=0
 DUMP_SPEC=
 
 # TODO: --srpm
@@ -49,12 +47,6 @@ function cleanup
     fi
 }
 
-function abort
-{
-    echo "*** ABORT..." "$@" 1>&2
-    exit 1
-}
-
 function parse_arguments
 {
     while [ $# -gt 0 ]; do
@@ -70,7 +62,7 @@ function parse_arguments
 	        OUTPUTDIR=$(echo $1 | sed 's/--output-dir=//')
 		;;
             --release=*)
-	        RELEASE=$(echo $1 | sed 's/--release=//')
+	        SRPMIX_RELEASE=$(echo $1 | sed 's/--release=//')
 		;;
 	    --dump-spec)
 	        DUMP_SPEC=1
@@ -83,60 +75,30 @@ function parse_arguments
     done
 
     if test "x$NAME" = "x"; then
-	abort "No name for the weakview"
+	srpmix_abort "No name for the weakview"
     fi
 
     if test "x$1" != "x"; then
 	print_usage 1>&2
-	abort "Too many arguments"
+	srpmix_abort "Too many arguments"
     fi
 
     if test "x$OUTPUTDIR" = "x"; then
 	OUTPUTDIR=.
     fi
     if test ! -d "${OUTPUTDIR}"; then
-	abort "No such directory: ${OUTPUTDIR}"
+	srpmix_abort "No such directory: ${OUTPUTDIR}"
     fi
-}
-
-function verify_commands
-{
-    while [ $# -gt 0 ]; do
-	if which $1 > /dev/null 2>&1; then
-	    :
-	else
-	    echo "cannot find $1" 1>&2
-	    abort
-	fi
-	shift 
-    done
 }
 
 function try_source
 {
     source $1
     if test $? != 0; then
-        abort "cannot find $1"
+        echo "*** ABORT..." "cannot find $1" 1>&2
 	exit 1
     fi
 }
-
-SCM='(begin 
- (define (kget kl ky) 
-   (cond ((null? kl) #f)
-	 ((eq? (car kl) ky) (cadr kl))
-	 (else (kget (cdr kl) ky))))
- (let loop ((r (read)))
-      (unless (eof-object? r)
-	(when (and (list? r)
-		   (eq? (car r) `srpmix-wrap)
-		   (not (null? (cdr r)))
-		   (eq? (cadr r) `name))
-	  (format #t "~a ~a ~a\n" 
-		  (kget r :package)
-		  (kget r :version)
-		  (kget r :release)))
-	(loop (read)))))'
 
 function create_dist_weakview
 {
@@ -154,7 +116,7 @@ function create_dist_weakview
 	
     rootdir=${SRPMIX_ROOT_DIR}
     distdir=${SRPMIX_ROOT_DIR}/dists
-
+    builddistdir_body="srpmix-weakview-dist-$name-$SRPMIX_VERSION-$SRPMIX_RELEASE/$distdir/$name"
 
     cat > $spec <<EOF
 Summary: Srpmix weakview for $name distribution
@@ -175,29 +137,31 @@ License: Unknown
 Srpmix weakview for $name distribution.
 
 %prep
-rm -rf %{_builddir}/srpmix-weakview-dist-$name-$SRPMIX_VERSION-$SRPMIX_RELEASE/$distdir/$name
+builddistdir=%{_builddir}/$builddistdir_body
+rm -rf \$builddistdir
 
 %build
-source libsrpmix.sh
-
-builddistdir=%{_builddir}/srpmix-weakview-dist-$name-$SRPMIX_VERSION-$SRPMIX_RELEASE/$distdir/$name
+builddistdir=%{_builddir}/$builddistdir_body
 mkdir -p \$builddistdir/packages
+
 EOF
 
-${GOSH} -e "${SCM}" | while read package version release; do
+# in %build
+srpmix_distmap_to_pvr | while read package version release; do
   # Make link relative
   d="../../.."$(srpmix_srcdir $package $version $release | sed -e "s;$rootdir;;")
   echo "ln -sf $d \$builddistdir/packages/$package"
 done >> $spec
 
+
     cat >> $spec <<EOF
 %install
-builddistdir=%{_builddir}/srpmix-weakview-dist-$name-$SRPMIX_VERSION-$SRPMIX_RELEASE/$distdir/$name
+builddistdir=%{_builddir}/$builddistdir_body
 
 rm -rf \$RPM_BUILD_ROOT
 mkdir -p \$RPM_BUILD_ROOT/$distdir/$name
 
-rsync -va %{_builddir}/srpmix-weakview-dist-$name-$SRPMIX_VERSION-$SRPMIX_RELEASE/$distdir/$name \$RPM_BUILD_ROOT/$distdir
+rsync -va \$builddistdir \$RPM_BUILD_ROOT/$distdir
 
 %files
 %defattr(-,root,root)
@@ -218,13 +182,12 @@ EOF
 
 function main
 {
-    verify_commands "${RPMBUILD}"
-    verify_commands "${GOSH}"
+    srpmix_verify_commands "${RPMBUILD}" "${GOSH}"
     parse_arguments "$@"
-    trap cleanup 0
 
     if test "x${DUMP_SPEC}" = "x"; then
 	TMPDIR=`mktemp -d`
+	trap cleanup 0
 	install -d $TMPDIR/{SPECS,BUILD,SOURCES,SRPMS}
     fi
 
diff --git a/srpmix/trunk/src/srpmix-wrap b/srpmix/trunk/src/srpmix-wrap
--- a/srpmix/trunk/src/srpmix-wrap
+++ b/srpmix/trunk/src/srpmix-wrap
@@ -27,16 +27,15 @@ RPMBUILD=rpmbuild
 LIBSRPMIX=libsrpmix.sh
 OUTPUTDIR=
 TMPDIR=
-RELEASE=0
 JUST_PRINT=
 DUMP_SPEC=
 
 function print_usage
 {
     echo "Usage: "
-    echo "  srpmix-dist [--help|-h]"
-    echo "  srpmix-dist [--dump-spec|--just-print] [SRPMS...]"
-    echo "  srpmix-dist [--output-dir=OUTPUTDIR] [--release=RELEASE] [SRPMS...]"
+    echo "  srpmix-wrap [--help|-h]"
+    echo "  srpmix-wrap [--dump-spec|--just-print] [SRPMS...]"
+    echo "  srpmix-wrap [--output-dir=OUTPUTDIR] [--release=RELEASE] [SRPMS...]"
     echo ""
     echo "  If SRPMS is not given, standard input is"
     echo "  used for the list of source packages."
@@ -48,12 +47,6 @@ function cleanup
     if test -d "$TMPDIR"; then
         rm -rf $TMPDIR || true
     fi
-}
-
-function abort
-{
-    echo "*** ABORT..." "$@" 1>&2
-    exit 1
 }
 
 function parse_arguments
@@ -68,7 +61,7 @@ function parse_arguments
 	        OUTPUTDIR=$(echo $1 | sed 's/--output-dir=//')
 		;;
             --release=*)
-	        RELEASE=$(echo $1 | sed 's/--release=//')
+	        SRPMIX_RELEASE=$(echo $1 | sed 's/--release=//')
 		;;
 	    --just-print)
 	        JUST_PRINT=1
@@ -94,7 +87,7 @@ function parse_arguments
     if test "x${JUST_PRINT}" != "x" \
 	-a "x${DUMP_SPEC}" != "x"; then
 	print_usage 1>&2
-	abort "Specify either --just-print or --dump-spec"
+	srpmix_abort "Specify either --just-print or --dump-spec"
     fi
 
     
@@ -102,28 +95,15 @@ function parse_arguments
 	OUTPUTDIR=.
     fi
     if test ! -d "${OUTPUTDIR}"; then
-	abort "No such directory: ${OUTPUTDIR}"
+	srpmix_abort "No such directory: ${OUTPUTDIR}"
     fi
-}
-
-function verify_commands
-{
-    while [ $# -gt 0 ]; do
-	if which $1 > /dev/null 2>&1; then
-	    :
-	else
-	    echo "cannot find $1" 1>&2
-	    abort
-	fi
-	shift 
-    done
 }
 
 function try_source
 {
     source $1
     if test $? != 0; then
-        abort "cannot find $1"
+        echo "*** ABORT..." "cannot find $1" 1>&2
 	exit 1
     fi
 }
@@ -275,13 +255,13 @@ EOF
 
 function main
 {
-    verify_commands "${RPMBUILD}"
+    srpmix_verify_commands "${RPMBUILD}"
     parse_arguments "$@"
-    trap cleanup 0
 
     if test "x${JUST_PRINT}" = "x" \
 	-o "x${DUMP_SPEC}" = "x"; then
 	TMPDIR=`mktemp -d`
+	trap cleanup 0
 	install -d $TMPDIR/{SPECS,BUILD,SOURCES,SRPMS}
     fi
 
@@ -290,7 +270,7 @@ function main
         if test -f "$srpm"; then
 	    wrap_srpm "$srpm"
         else
-            abort "No such file: $srpm"
+            srpmix_abort "No such file: $srpm"
         fi
     done
 }
